### ISSUE TITLE
request for a session middleware

### ISSUE THREAD

**Issue by xialvjun** [volatile/volatile#1]
1. I hope you can ref to `nodejs koa` in this repo's description and readme. That will make this framework more popular.

2. request for a session middleware.  Since golang is a strong static language which make we can not assign a new property to a struct (we can not `context.Session = XXX` if `Session` is not a defined filed in `Context`), maybe we can store the session in a hashmap in the middleware:

```go
package main

import (
	"github.com/volatile/core"
	"github.com/volatile/session"
	"github.com/volatile/route"
)

func main() {
	session.Use(nil)

	route.Post("^/login$", func(c *core.Context, params map[string]string) {
		user := getUser(c)
                // set-cookie ["sid", sid] header to c, and store user to session package: session.Map[sid]=user
		session.Set(c, user)
	})

        route.Get("/", func(c *core.Context, params map[]string)string) {
                // session.Get(c) equals to session.Map[c.Request.Cookie.get("sid")]
                fmt.Println(session.Get(c).String())
        }

	core.Run()
}
```

Of course, we can make `session.Map` to `session.map`, make it private.
And since `session.map` may be accessed by mutiple goroutine at the same time, it should be wraped in a `Mutex`

3. Another suggesstion: just like `net/http`,  we can use it's default Server, we also have the ability to create a new Server, so I hope `volatile` and `session` can do it too. Of course, `cors` doesn't need to do it since it is just a function, there is no struct in the package.

**Comment by xthezealot** [comment]
Sorry but I don't think I'll invest in a Volatile improvement for several reasons:
- In the current stage, Volatile Core is not relevant anymore as the [context](https://golang.org/pkg/context/) package is now part of the standard library and it's easy to use.
- The Volatile middlewares and helpers have zero compatibility with [net/http](https://golang.org/pkg/net/http/), that's why I begun to rewrite them in [github.com/gowww](https://github.com/gowww).
- After 7 years, Node.js (and all the JS ecosystem) is unfortunately still more suited for quick web & mobile development IMHO.
- Serverless is sufficiently promising to move focus on this approach.
- I'm very busy at this time. 😅

For sessions, [github.com/gorilla/sessions](https://github.com/gorilla/sessions) is fairly complete (and usable with Volatile):

```Go
import (
	"net/http"

	"github.com/gorilla/sessions"
	"github.com/volatile/core"
	"github.com/volatile/route"
)

var store = sessions.NewCookieStore([]byte("something-very-secret"))

func main() {
	route.Post("^/login$", func(c *core.Context) {
		user := getUser(c)
		sess, _ := store.Get(c.Request, "auth")
		sess.Values["user"] = user
		sess.Save(c.Request, c.ResponseWriter)
	})

	route.Get("/", func(c *core.Context) {
		sess, _ := store.Get(c.Request, "auth")
		fmt.Println(sess.Values["user"]) // Calling .String() is useless as fmt.Println searches for this method by itself.
	}

	core.Run()
}
```
